---

- name: Gather facts of all mounts, including non-disk mounts
  script: facts/all_mounts.py
  args:
    executable: "{{ debian10cis_python_executable }}"
  changed_when: false
  check_mode: false
  register: all_mounts
